sudo: false

language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - node
  - 6
install:
  - make deps
script:
  - make test
  - make lint
notifications:
  email:
    - phihag@phihag.de

